version: "3"
services:
  test:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    env_file:
      - test.env
    depends_on:
      - db-test
    networks:
      test-net:
        ipv4_address: 172.28.0.5

  db-test:
    image: mysql:latest
    volumes:
      - /Users/earthzaza/Desktop/earthwork/test-flask/DB_TEST/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: Sdpxdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: db4test$
      MYSQL_ROOT_PASSWORD: root
    networks:
      test-net:
        ipv4_address: 172.28.0.4
networks:
  test-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16